GET http://localhost:3000/recipes

###
GET http://localhost:3000/ingredients


###

POST http://localhost:3000/recipes
Content-Type: application/json

{
        "name": "Ensalada Veggie 1",
        "recipeDescription": "Cortas lechuga, tomate y queso, le pones un poco de vinagre y la mezclas",
        "celiac":false,
        "vegetarian":true,
        "vegan":false,
        "porciones":2,
        "idIngredient":["62601f26566535e549fec517"]
}
###
POST http://localhost:3000/ingredients
Content-Type: application/json

{
        "name": "Tomatlkhjge"
}

###

DELETE  http://localhost:3000/recipes/6256dce02bb69c3b48a0a925
###

DELETE  http://localhost:3000/recipes/6255e4089f5f1f81d4a99915
###

DELETE  http://localhost:3000/recipes/6255e5611adcea882e2ac330
###

DELETE  http://localhost:3000/recipes/6255e6611adcea882e2ac336
###

DELETE  http://localhost:3000/recipes/6255e6f023070a9fd3f0a3d1
###

DELETE  http://localhost:3000/recipes/6256da563458a532521b4f87

###/
GET http://localhost:3000/recipes/6255e4089f5f1f81d4a99915
###

