@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7InVzZXJOYW1lIjoieW9wIiwicGFzc3dvcmQiOiJqdWVnb3M5ODciLCJlbWFpbCI6IkBnbWFpbGwuY29tIiwiX2lkIjoiNjI2ODA5Mzk0OGFkZGE1ODMzNjkzNWRmIiwiX192IjowfSwiaWF0IjoxNjUwOTg1MjczfQ.-XtjI2wVrwgGBtvs1J9yxqqUF2hMyBGEqzMaYLEwnMA

GET http://localhost:3000/recipes

###
GET http://localhost:3000/ingredients

###
GET http://localhost:3000/login


###

POST http://localhost:3000/recipes
Content-Type: application/json

{
        "name": "Ensalada Veggie 433",
        "recipeDescription": "Cortas lechuga, tomate y queso, le pones un poco de vinagre y la mezclas",
        "celiac":false,
        "vegetarian":true,
        "vegan":false,
        "porciones":2,
        "idIngredient":["62601f26566535e549fec517"]
}
###
POST http://localhost:3000/ingredients
Content-Type: application/json
Authorization: Bearer {{token}}
{
        "name": "quesito sancor"
}

###
POST http://localhost:3000/login
Content-Type: application/json

{
        "userName": "yop",
        "password":"juegos987",
        "email":"@gmaill.com"
}


###/
GET http://localhost:3000/recipes/6255e4089f5f1f81d4a99915
###

